# Generated by Django 5.2 on 2025-12-01 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_image_url', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('target_pet_type', models.CharField(blank=True, choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=10, null=True)),
                ('min_follower_count', models.IntegerField(default=0)),
                ('requested_at', models.DateTimeField()),
                ('application_deadline_at', models.DateField()),
                ('posting_start_at', models.DateField()),
                ('posting_end_at', models.DateField()),
                ('required_creator_count', models.IntegerField()),
                ('style_tags', models.CharField(blank=True, choices=[('outdoor', 'Outdoor'), ('energetic', 'Energetic'), ('no_preference', 'No Preference'), ('minimal', 'Minimal'), ('aesthetic', 'Aesthetic'), ('heartfelt', 'Heartfelt'), ('cozy', 'Cozy'), ('wholesome', 'Wholesome'), ('funny', 'Funny'), ('calm', 'Calm')], max_length=20, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignAcceptance',
            fields=[
                ('campaign_acceptance_id', models.AutoField(primary_key=True, serialize=False)),
                ('acceptance_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='myapp.campaign')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('deliverable_id', models.AutoField(primary_key=True, serialize=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('post_url', models.CharField(blank=True, max_length=255, null=True)),
                ('deliverable_status', models.CharField(choices=[('incomplete', 'Incomplete'), ('completed', 'Completed')], default='incomplete', max_length=10)),
                ('campaign_acceptance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='myapp.campaignacceptance')),
            ],
        ),
    ]
