# Generated by Django 5.2.4 on 2025-11-14 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=50)),
                ('login_password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('brand_pet_focus', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=50)),
                ('login_password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('pet_type', models.TextField()),
                ('sns_handle', models.CharField(max_length=50)),
                ('sns_url', models.TextField()),
                ('total_post_count', models.IntegerField()),
                ('follower_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=100)),
                ('product_image_url', models.TextField()),
                ('product_description', models.TextField()),
                ('target_pet_type', models.TextField()),
                ('min_follower_count', models.IntegerField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('application_deadline_at', models.DateField()),
                ('posting_start_at', models.DateField()),
                ('posting_end_at', models.DateField()),
                ('required_creator_count', models.IntegerField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.accountbrand')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_status', models.CharField(max_length=100)),
                ('applied_at', models.DateTimeField()),
                ('selected_at', models.DateTimeField()),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.campaign')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.accountcreator')),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField()),
                ('post_url', models.TextField()),
                ('deliverable_status', models.CharField(max_length=100)),
                ('campaign_acceptance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.campaignacceptance')),
            ],
        ),
    ]
